# Generated by Django 5.0.3 on 2024-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
