# Generated by Django 5.0.3 on 2024-03-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_college_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
